[package]
name = "bevy_paratrooper"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_rapier2d = "0.12.1"
bevy_prototype_lyon = "0.4.0"
rand = "0.8.5"
heron = "2.3.0"

[dependencies.bevy]
version = "0.6"
default-features = false
# These are the remaining default features other than `bevy_audio` and `mp3`
features = [
    "render",
    "bevy_winit",
    "bevy_gilrs",
    "png",
    "hdr",
    "filesystem_watcher",
    "x11"
]

[dependencies.bevy_kira_audio]
version = "0.8.0"
default-features = false
features = [
    "wav",
    "flac",
    "mp3",
    "ogg",
]

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3

