[package]
name = "bevy_paratrooper"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_prototype_lyon = "0.5.0"
rand = "0.8.5"
nrfind = "1.0.3"

[dependencies.bevy_rapier2d]
version = "0.13.2"
features = [
    "wasm-bindgen"
]

[dependencies.bevy]
version = "0.7"
#default-features = false
# These are the remaining default features other than `bevy_audio` and `mp3`
features = [
    "wav"
#    "render",
#    "bevy_winit",
#    "bevy_gilrs",
#    "png",
#    "hdr",
#    "filesystem_watcher",
#    "x11"
]

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies
[profile.dev.package."*"]
opt-level = 3

